/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Dynamic animation targeting per strict debugging rules.
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Avatar(props) {
  const group = useRef();

  // 1. Load the base Avaturn avatar model
  const { nodes, materials } = useGLTF('/models/avatar.glb');

  // 2. Load the external typing animation file dynamically
  const { animations: typingAnim } = useGLTF('/animations/typing.glb');

  // 3. Bind animations to the group ref
  const { actions } = useAnimations(typingAnim, group);

  // 4. Dynamic Animation Target (Stop Guessing Names)
  useEffect(() => {
    if (typingAnim && typingAnim.length > 0) {
      const clipName = typingAnim[0].name;
      console.log("Loaded Clip Name:", clipName); // For debugging
      const action = actions[clipName];
      if (action) {
        action.reset().fadeIn(0.5).play();
      }
    }
  }, [actions, typingAnim]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.avaturn_body.geometry}
        material={materials.avaturn_body_material}
        skeleton={nodes.avaturn_body.skeleton}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_glasses_0.geometry}
        material={materials.avaturn_glasses_0_material}
        skeleton={nodes.avaturn_glasses_0.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_glasses_1.geometry}
        material={materials.avaturn_glasses_1_material}
        skeleton={nodes.avaturn_glasses_1.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_hair_0.geometry}
        material={materials.avaturn_hair_0_material}
        skeleton={nodes.avaturn_hair_0.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_hair_1.geometry}
        material={materials.avaturn_hair_1_material}
        skeleton={nodes.avaturn_hair_1.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_shoes_0.geometry}
        material={materials.avaturn_shoes_0_material}
        skeleton={nodes.avaturn_shoes_0.skeleton}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_look_0.geometry}
        material={materials.avaturn_look_0_material}
        skeleton={nodes.avaturn_look_0.skeleton}
        castShadow
      />
    </group>
  );
}

export default Avatar;

useGLTF.preload('/models/avatar.glb');
useGLTF.preload('/animations/typing.glb');