/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Retargeted with clean bone name track transformation for Avaturn skeleton.
*/

import React, { useRef, useEffect, useMemo } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Avatar(props) {
  const group = useRef();

  // 1. Load the base Avaturn avatar model
  const { nodes, materials } = useGLTF('/models/avatar.glb');

  // 2. Load the external typing animation file
  const { animations: typingAnim } = useGLTF('/animations/typing.glb');

  // 3. Mutate and strip 'mixamorig' prefix from tracks BEFORE passing to useAnimations
  const retargetedAnimations = useMemo(() => {
    if (!typingAnim || typingAnim.length === 0) return [];

    return typingAnim.map((clip) => {
      // Clone the clip so we don't mutate raw cached data improperly
      const newClip = clip.clone();

      newClip.tracks.forEach((track) => {
        // Example: 'mixamorigHead.position' -> 'Head.position'
        // Example: 'mixamorigRightForeArm.quaternion' -> 'RightForeArm.quaternion'
        // Regex removes any occurrence of 'mixamorig' (with or without colon/underscore)
        track.name = track.name.replace(/mixamorig:?/i, '');

        // Ensure the bone name starts with an uppercase letter to match Avaturn skeleton convention
        const parts = track.name.split('.');
        if (parts[0]) {
          parts[0] = parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
          track.name = parts.join('.');
        }
      });

      return newClip;
    });
  }, [typingAnim]);

  // 4. Bind retargeted animations to the group ref
  const { actions } = useAnimations(retargetedAnimations, group);

  // 5. Automatically play the typing animation on mount
  useEffect(() => {
    if (retargetedAnimations && retargetedAnimations.length > 0) {
      const clipName = retargetedAnimations[0].name;
      const action = actions[clipName];
      if (action) {
        console.log(`▶️ Successfully playing retargeted clip: "${clipName}"`);
        action.reset().fadeIn(0.5).play();
      }
    }
  }, [actions, retargetedAnimations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.avaturn_body.geometry}
        material={materials.avaturn_body_material}
        skeleton={nodes.avaturn_body.skeleton}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_glasses_0.geometry}
        material={materials.avaturn_glasses_0_material}
        skeleton={nodes.avaturn_glasses_0.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_glasses_1.geometry}
        material={materials.avaturn_glasses_1_material}
        skeleton={nodes.avaturn_glasses_1.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_hair_0.geometry}
        material={materials.avaturn_hair_0_material}
        skeleton={nodes.avaturn_hair_0.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_hair_1.geometry}
        material={materials.avaturn_hair_1_material}
        skeleton={nodes.avaturn_hair_1.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_shoes_0.geometry}
        material={materials.avaturn_shoes_0_material}
        skeleton={nodes.avaturn_shoes_0.skeleton}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_look_0.geometry}
        material={materials.avaturn_look_0_material}
        skeleton={nodes.avaturn_look_0.skeleton}
        castShadow
      />
    </group>
  );
}

export default Avatar;

useGLTF.preload('/models/avatar.glb');
useGLTF.preload('/animations/typing.glb');