/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with external Mixamo animation blending and clip controls.
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Avatar({ animation = 'typing', ...props }) {
  const group = useRef();

  // 1. Load the base Avaturn avatar mesh & skeleton
  const { nodes, materials } = useGLTF('/models/avatar.glb');

  // 2. Load the external Mixamo animation files
  const { animations: typingAnimations } = useGLTF('/animations/Typing.glb');
  const { animations: wavingAnimations } = useGLTF('/animations/Waving.glb');

  // 3. Rename clips to clean semantic names ('typing' and 'waving')
  if (typingAnimations && typingAnimations[0]) {
    typingAnimations[0].name = 'typing';
  }
  if (wavingAnimations && wavingAnimations[0]) {
    wavingAnimations[0].name = 'waving';
  }

  // 4. Combine animation clips into a single array
  const combinedAnimations = [
    ...(typingAnimations || []),
    ...(wavingAnimations || []),
  ];

  // 5. Bind animations to the group ref
  const { actions } = useAnimations(combinedAnimations, group);

  // 6. Automatically play and cross-fade animations on mount or when animation prop changes
  useEffect(() => {
    const currentAction = actions[animation] || actions['typing'] || actions[Object.keys(actions)[0]];

    if (currentAction) {
      currentAction.reset().fadeIn(0.5).play();
    }

    return () => {
      if (currentAction) {
        currentAction.fadeOut(0.5);
      }
    };
  }, [actions, animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.avaturn_body.geometry}
        material={materials.avaturn_body_material}
        skeleton={nodes.avaturn_body.skeleton}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_glasses_0.geometry}
        material={materials.avaturn_glasses_0_material}
        skeleton={nodes.avaturn_glasses_0.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_glasses_1.geometry}
        material={materials.avaturn_glasses_1_material}
        skeleton={nodes.avaturn_glasses_1.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_hair_0.geometry}
        material={materials.avaturn_hair_0_material}
        skeleton={nodes.avaturn_hair_0.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_hair_1.geometry}
        material={materials.avaturn_hair_1_material}
        skeleton={nodes.avaturn_hair_1.skeleton}
        castShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_shoes_0.geometry}
        material={materials.avaturn_shoes_0_material}
        skeleton={nodes.avaturn_shoes_0.skeleton}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.avaturn_look_0.geometry}
        material={materials.avaturn_look_0_material}
        skeleton={nodes.avaturn_look_0.skeleton}
        castShadow
      />
    </group>
  );
}

export default Avatar;

useGLTF.preload('/models/avatar.glb');
useGLTF.preload('/animations/Typing.glb');
useGLTF.preload('/animations/Waving.glb');