/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Chair component with root primitive traversal to inspect and preserve native transformations.
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { scene } = useGLTF('/models/Chair.glb')
  // Clone scene so multiple instances or transforms don't mutate cached GLTF
  const clone = React.useMemo(() => scene.clone(), [scene])

  return (
    <primitive object={clone} {...props} />
  )
}

export default Chair
useGLTF.preload('/models/Chair.glb')
