/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Centered mesh pivot geometry so scaling/rotation happens around the chair center, not an offset origin.
*/

import React from 'react'
import { useGLTF, Center } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('/models/Chair.glb')
  return (
    <group {...props} dispose={null}>
      <Center bottom>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh'].geometry}
          material={materials.Office_Cha}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh_1'].geometry}
          material={materials.Office_Cha_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh_2'].geometry}
          material={materials.Office_Cha_2}
        />
      </Center>
    </group>
  )
}

export default Chair
useGLTF.preload('/models/Chair.glb')
