/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Fixed: Native Chair.glb raw vertices were exported offset at X ~ 336, Y ~ 0, Z ~ -213.
We subtract the offset [-336.0, 0, 213.0] so (0,0,0) is exactly the chair's center!
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

// Exact geometric centroid offsets from Chair.glb accessors
const CHAIR_OFFSET_X = -336.0;
const CHAIR_OFFSET_Y = 0;
const CHAIR_OFFSET_Z = 213.0;
// Natural scaling factor to bring 40-unit Blender chair to standard 0.8m world units
const NORMALIZED_CHAIR_SCALE = 0.025;

export function Chair(props) {
  const { nodes, materials } = useGLTF('/models/Chair.glb')
  return (
    <group {...props} dispose={null}>
      {/* Centering and normalizing sub-group */}
      <group scale={NORMALIZED_CHAIR_SCALE} position={[0, 0, 0]}>
        <group position={[CHAIR_OFFSET_X, CHAIR_OFFSET_Y, CHAIR_OFFSET_Z]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh'].geometry}
            material={materials.Office_Cha}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_1'].geometry}
            material={materials.Office_Cha_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_2'].geometry}
            material={materials.Office_Cha_2}
          />
        </group>
      </group>
    </group>
  )
}

export default Chair
useGLTF.preload('/models/Chair.glb')
