/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Path corrected to absolute public folder: /models/Desk.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('/models/Desk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Desk.geometry}
        material={materials.Material}
        scale={100}
      />
    </group>
  )
}

export default Desk
useGLTF.preload('/models/Desk.glb')