/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Centered mesh pivot geometry so scaling/rotation happens around the desk center.
*/

import React from 'react'
import { useGLTF, Center } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('/models/Desk.glb')
  return (
    <group {...props} dispose={null}>
      <Center bottom>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk.geometry}
          material={materials.Material}
          scale={100}
        />
      </Center>
    </group>
  )
}

export default Desk
useGLTF.preload('/models/Desk.glb')